name = "mitch478-xyz"
compatibility_date = "2025-08-15"
main = "workers-site/index.js"

[build]
command = "npm run build"
cwd = "./"

[site]
bucket = "out" 

[[routes]]
pattern = "mitch478.xyz"
custom_domain = true